using System.Net;
using System.Text;
using System.Xml.Linq;
using Drederick.Recon;

namespace Drederick.Ops;

/// <summary>
/// A service-level finding extracted from a Tenable scan export.
/// </summary>
public sealed class TenableService
{
    public int Port { get; init; }
    public string Protocol { get; init; } = "tcp";
    public string? ServiceName { get; init; }
    public int PluginId { get; init; }
    public string? PluginName { get; init; }
    /// <summary>0 = info, 1 = low, 2 = medium, 3 = high, 4 = critical.</summary>
    public int Severity { get; init; }
    public IReadOnlyList<string> Cves { get; init; } = Array.Empty<string>();
}

/// <summary>
/// Per-host scan data extracted from a Tenable scan export.
/// </summary>
public sealed class TenableHostScan
{
    public string IpAddress { get; init; } = "";
    public string? Fqdn { get; init; }
    public string? Os { get; init; }
    public IReadOnlyList<TenableService> Services { get; init; } = Array.Empty<TenableService>();
}

/// <summary>
/// Result of parsing a Tenable scan export file.
/// </summary>
public sealed class TenableImportResult
{
    /// <summary>Unique IP addresses discovered in the scan.</summary>
    public IReadOnlyList<string> Hosts { get; init; } = Array.Empty<string>();

    /// <summary>Per-host scan details including services and CVEs.</summary>
    public IReadOnlyList<TenableHostScan> HostScans { get; init; } = Array.Empty<TenableHostScan>();

    /// <summary>Source file path or description used for diagnostics.</summary>
    public string Source { get; init; } = "";

    /// <summary>Detected format: "nessus-xml" or "csv".</summary>
    public string Format { get; init; } = "";
}

/// <summary>
/// Parses Tenable scan export files (Nessus XML <c>.nessus</c> format or Tenable CSV)
/// and extracts host IPs, service information, and CVE references. The extracted
/// data can be used to populate the scan target list and to pre-seed the
/// <see cref="Memory.KnowledgeBase"/> so subsequent recon tools can skip
/// re-discovering already-known service surfaces.
/// </summary>
public static class TenableScanImporter
{
    /// <summary>
    /// Parse a Tenable scan export file at <paramref name="filePath"/>. Accepts
    /// Nessus XML (<c>.nessus</c>) and Tenable CSV formats; the format is
    /// auto-detected from the file content. Throws <see cref="FileNotFoundException"/>
    /// if the file does not exist and <see cref="InvalidOperationException"/> if the
    /// format cannot be recognised or the XML/CSV is malformed.
    /// </summary>
    public static TenableImportResult Parse(string filePath)
    {
        if (!File.Exists(filePath))
            throw new FileNotFoundException($"Tenable import file not found: {filePath}", filePath);

        const long MaxFileSizeBytes = 100 * 1024 * 1024; // 100 MB
        var info = new FileInfo(filePath);
        if (info.Length > MaxFileSizeBytes)
            throw new InvalidOperationException(
                $"Tenable import file '{filePath}' is {info.Length / (1024 * 1024)} MB, " +
                "which exceeds the 100 MB safety cap.");

        var content = File.ReadAllText(filePath);
        return ParseContent(content, filePath);
    }

    /// <summary>
    /// Parse raw Tenable scan export <paramref name="content"/>. Accepts Nessus XML
    /// and Tenable CSV. <paramref name="source"/> is used only for diagnostics.
    /// </summary>
    internal static TenableImportResult ParseContent(string content, string source = "<memory>")
    {
        var trimmed = content.TrimStart();

        if (trimmed.StartsWith("<?xml", StringComparison.OrdinalIgnoreCase) ||
            trimmed.StartsWith("<NessusClientData_v2", StringComparison.OrdinalIgnoreCase) ||
            trimmed.StartsWith("<NessusClientData", StringComparison.OrdinalIgnoreCase))
        {
            return ParseNessusXml(content, source);
        }

        var firstLine = trimmed.Split('\n', 2)[0].Trim();
        if (IsNessusCsvHeader(firstLine))
            return ParseCsv(content, source);

        throw new InvalidOperationException(
            $"Unrecognized Tenable scan format in '{source}'. " +
            "Supported formats: Nessus XML (.nessus) and Tenable CSV export.");
    }

    /// <summary>
    /// Parse a Nessus XML export (the <c>.nessus</c> format generated by both
    /// Tenable.io and Tenable.sc). Extracts one <see cref="TenableHostScan"/> per
    /// <c>ReportHost</c> element. Non-IP host names are skipped.
    /// </summary>
    internal static TenableImportResult ParseNessusXml(string xmlContent, string source)
    {
        XDocument doc;
        try { doc = XDocument.Parse(xmlContent); }
        catch (Exception ex)
        {
            throw new InvalidOperationException(
                $"Failed to parse Nessus XML from '{source}': {ex.Message}", ex);
        }

        var hostScans = new List<TenableHostScan>();

        foreach (var reportHost in doc.Descendants("ReportHost"))
        {
            var nameAttr = reportHost.Attribute("name")?.Value?.Trim();

            var hostIpTag = reportHost
                .Descendants("tag")
                .FirstOrDefault(t => t.Attribute("name")?.Value == "host-ip")
                ?.Value?.Trim();

            var fqdn = reportHost
                .Descendants("tag")
                .FirstOrDefault(t => t.Attribute("name")?.Value == "host-fqdn")
                ?.Value?.Trim();
            if (string.IsNullOrEmpty(fqdn)) fqdn = null;

            var os = reportHost
                .Descendants("tag")
                .FirstOrDefault(t => t.Attribute("name")?.Value is "operating-system" or "os")
                ?.Value?.Trim();
            if (string.IsNullOrEmpty(os)) os = null;

            // Prefer the explicit host-ip tag; fall back to the name attribute.
            // Only accept valid IP addresses — skip pure hostnames in both positions.
            string? ip = null;
            if (!string.IsNullOrEmpty(hostIpTag) && IPAddress.TryParse(hostIpTag, out _))
                ip = hostIpTag;
            else if (!string.IsNullOrEmpty(nameAttr) && IPAddress.TryParse(nameAttr, out _))
                ip = nameAttr;
            if (ip is null) continue;

            var services = new List<TenableService>();

            foreach (var item in reportHost.Elements("ReportItem"))
            {
                if (!int.TryParse(item.Attribute("port")?.Value, out var port)) continue;

                var protocol = item.Attribute("protocol")?.Value ?? "tcp";
                var svcName = item.Attribute("svc_name")?.Value;
                if (string.IsNullOrEmpty(svcName)) svcName = null;

                int.TryParse(item.Attribute("pluginID")?.Value, out var pluginId);
                var pluginName = item.Attribute("pluginName")?.Value;
                if (string.IsNullOrEmpty(pluginName)) pluginName = null;

                int.TryParse(item.Attribute("severity")?.Value, out var severity);

                var cves = item.Elements("cve")
                    .Select(e => e.Value.Trim())
                    .Where(v => !string.IsNullOrEmpty(v))
                    .ToList();

                services.Add(new TenableService
                {
                    Port = port,
                    Protocol = protocol,
                    ServiceName = svcName,
                    PluginId = pluginId,
                    PluginName = pluginName,
                    Severity = severity,
                    Cves = cves,
                });
            }

            hostScans.Add(new TenableHostScan
            {
                IpAddress = ip,
                Fqdn = fqdn,
                Os = os,
                Services = services,
            });
        }

        return new TenableImportResult
        {
            Hosts = hostScans.Select(h => h.IpAddress).Distinct().ToList(),
            HostScans = hostScans,
            Source = source,
            Format = "nessus-xml",
        };
    }

    /// <summary>
    /// Parse a Tenable CSV export. Requires at minimum a <c>Host</c> column; rows
    /// whose <c>Host</c> value is not a valid IP address are skipped. CVE values and
    /// Risk levels are read from <c>CVE</c> and <c>Risk</c> columns when present.
    /// </summary>
    internal static TenableImportResult ParseCsv(string csvContent, string source)
    {
        var lines = csvContent.Split('\n', StringSplitOptions.RemoveEmptyEntries);
        if (lines.Length == 0)
            return new TenableImportResult { Source = source, Format = "csv" };

        var header = SplitCsvLine(lines[0]);
        int hostIdx = FindColumnIndex(header, "Host");
        int portIdx = FindColumnIndex(header, "Port");
        int protocolIdx = FindColumnIndex(header, "Protocol");
        int pluginIdIdx = FindColumnIndex(header, "Plugin ID");
        int pluginNameIdx = FindColumnIndex(header, "Name");
        int cveIdx = FindColumnIndex(header, "CVE");
        int riskIdx = FindColumnIndex(header, "Risk");

        if (hostIdx < 0)
            throw new InvalidOperationException(
                $"Tenable CSV from '{source}' is missing the required 'Host' column.");

        var hostServices = new Dictionary<string, List<TenableService>>(StringComparer.OrdinalIgnoreCase);

        for (int i = 1; i < lines.Length; i++)
        {
            var line = lines[i].Trim();
            if (string.IsNullOrEmpty(line)) continue;

            var cols = SplitCsvLine(line);
            if (cols.Count <= hostIdx) continue;

            var host = cols[hostIdx].Trim();
            if (!IPAddress.TryParse(host, out _)) continue;

            if (!hostServices.ContainsKey(host))
                hostServices[host] = new List<TenableService>();

            int port = 0;
            if (portIdx >= 0 && portIdx < cols.Count)
                int.TryParse(cols[portIdx].Trim(), out port);

            var protocol = "tcp";
            if (protocolIdx >= 0 && protocolIdx < cols.Count)
            {
                var p = cols[protocolIdx].Trim();
                if (!string.IsNullOrEmpty(p)) protocol = p.ToLowerInvariant();
            }

            int pluginId = 0;
            if (pluginIdIdx >= 0 && pluginIdIdx < cols.Count)
                int.TryParse(cols[pluginIdIdx].Trim(), out pluginId);

            string? pluginName = null;
            if (pluginNameIdx >= 0 && pluginNameIdx < cols.Count)
            {
                var pn = cols[pluginNameIdx].Trim();
                if (!string.IsNullOrEmpty(pn)) pluginName = pn;
            }

            var cves = new List<string>();
            if (cveIdx >= 0 && cveIdx < cols.Count)
            {
                var cveVal = cols[cveIdx].Trim();
                if (!string.IsNullOrEmpty(cveVal)) cves.Add(cveVal);
            }

            var severity = 0;
            if (riskIdx >= 0 && riskIdx < cols.Count)
            {
                severity = cols[riskIdx].Trim().ToLowerInvariant() switch
                {
                    "critical" => 4,
                    "high" => 3,
                    "medium" => 2,
                    "low" => 1,
                    _ => 0,
                };
            }

            // Skip rows that carry neither a port number nor a plugin ID — these are
            // host-level metadata rows with no actionable service information.
            if (port == 0 && pluginId == 0) continue;

            hostServices[host].Add(new TenableService
            {
                Port = port,
                Protocol = protocol,
                PluginId = pluginId,
                PluginName = pluginName,
                Severity = severity,
                Cves = cves,
            });
        }

        var hostScans = hostServices
            .Select(kv => new TenableHostScan { IpAddress = kv.Key, Services = kv.Value })
            .ToList();

        return new TenableImportResult
        {
            Hosts = hostScans.Select(h => h.IpAddress).ToList(),
            HostScans = hostScans,
            Source = source,
            Format = "csv",
        };
    }

    /// <summary>
    /// Convert a <see cref="TenableImportResult"/> to a list of
    /// <see cref="HostFinding"/> objects suitable for seeding
    /// <see cref="Memory.KnowledgeBase"/>. Port data from the Tenable scan is
    /// mapped onto the <see cref="NmapResult.OpenPorts"/> list so the adaptive
    /// runner can treat them as pre-discovered services without re-scanning.
    /// Only ports with a non-zero port number are included. Duplicate port/protocol
    /// pairs for the same host are deduplicated.
    /// </summary>
    public static IReadOnlyList<HostFinding> ToHostFindings(TenableImportResult result)
    {
        var findings = new List<HostFinding>(result.HostScans.Count);
        var now = DateTimeOffset.UtcNow.ToString("o");

        foreach (var hostScan in result.HostScans)
        {
            var seen = new HashSet<(int, string)>();
            var ports = new List<NmapPort>();

            foreach (var svc in hostScan.Services)
            {
                if (svc.Port == 0) continue;
                if (!seen.Add((svc.Port, svc.Protocol))) continue;

                ports.Add(new NmapPort
                {
                    Port = svc.Port,
                    Protocol = svc.Protocol,
                    Service = svc.ServiceName,
                    Product = svc.PluginName,
                });
            }

            var finding = new HostFinding
            {
                Target = hostScan.IpAddress,
                Started = now,
                Finished = now,
            };

            if (ports.Count > 0)
            {
                finding.Nmap = new NmapResult
                {
                    ReturnCode = 0,
                    OpenPorts = ports,
                };
            }

            findings.Add(finding);
        }

        return findings;
    }

    private static bool IsNessusCsvHeader(string firstLine) =>
        firstLine.StartsWith("Plugin ID", StringComparison.OrdinalIgnoreCase) ||
        firstLine.Contains(",Host,", StringComparison.OrdinalIgnoreCase);

    private static int FindColumnIndex(IList<string> headers, string name)
    {
        for (int i = 0; i < headers.Count; i++)
        {
            if (string.Equals(headers[i].Trim(), name, StringComparison.OrdinalIgnoreCase))
                return i;
        }
        return -1;
    }

    /// <summary>
    /// Split a single CSV line into fields, respecting RFC 4180 double-quote
    /// escaping. A <c>""</c> sequence inside a quoted field is treated as a
    /// literal <c>"</c> character.
    /// </summary>
    internal static List<string> SplitCsvLine(string line)
    {
        var fields = new List<string>();
        var current = new StringBuilder();
        bool inQuotes = false;

        for (int i = 0; i < line.Length; i++)
        {
            var ch = line[i];
            if (ch == '"')
            {
                if (inQuotes && i + 1 < line.Length && line[i + 1] == '"')
                {
                    current.Append('"');
                    i++;
                }
                else
                {
                    inQuotes = !inQuotes;
                }
            }
            else if (ch == ',' && !inQuotes)
            {
                fields.Add(current.ToString());
                current.Clear();
            }
            else
            {
                current.Append(ch);
            }
        }

        fields.Add(current.ToString());
        return fields;
    }
}
